""" The 'Semantic GraphRAG' Pipeline
 * Local Chunks: Embedded for specific "needle-in-a-haystack" retrieval.
 * Communities: Created via K-Means clustering of those chunks.
 * Community Reports: Generated by Llama 3.1 8B to describe the "theme" of the cluster.
 * Global Embeddings: The reports themselves are embedded, allowing you to search for themes rather than just keywords.
 """
import os
import json
import re
import numpy as np
import ollama
from langchain_text_splitters import RecursiveCharacterTextSplitter
from sklearn.cluster import KMeans
from langchain_experimental.text_splitter import SemanticChunker
# from langchain_community.embeddings import OllamaEmbeddings
from langchain_ollama import OllamaEmbeddings
from pypdf import PdfReader
from sklearn.cluster import KMeans

# The Corpus: EU (Horizontal), CoE (Treaty), and Switzerland (FADP + Guidelines)
SOURCES = {
    "EU_AI_Act": "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32024R1689",
    "CoE_AI_Convention": "https://rm.coe.int/1680afae3c",
    "Swiss_FADP": "https://www.fedlex.admin.ch/filestore/fedlex.data.admin.ch/eli/cc/2022/491/20230901/en/pdf-a/fedlex-data-admin-ch-eli-cc-2022-491-20230901-en-pdf-a.pdf",
    "Swiss_AI_Guidelines": "https://www.sbfi.admin.ch/dam/sbfi/en/dokumente/2020/11/leitlinien-ki.pdf"
}

    # [GIN] 2026/03/12 - 09:09:18 | 200 |     86.0213ms |       127.0.0.1 | POST     "/api/embeddings"
    # time=2026-03-12T09:09:20.962+01:00 level=WARN source=types.go:571 msg="invalid option provided" option=tfs_z
    # time=2026-03-12T09:09:20.962+01:00 level=WARN source=types.go:571 msg="invalid option provided" option=mirostat_eta
    # time=2026-03-12T09:09:20.962+01:00 level=WARN source=types.go:571 msg="invalid option provided" option=mirostat_tau
    # time=2026-03-12T09:09:20.962+01:00 level=WARN source=types.go:571 msg="invalid option provided" option=mirostat

# --- CONFIGURATION ---
# Using 7B class for reasoning and mxbai-embed-large
MODELS = {
    "embed": "mxbai-embed-large:latest", # nomic-embed-text --> does not support batch embedding 
    "slm": "llama3.1:8b"
}

def get_semantic_chunks(path):
    print(f"Semantically chunking {path}...")

    # 1. Load PDF text
    reader = PdfReader(path)
    text = "".join([p.extract_text() or "" for p in reader.pages]).strip()

    if len(text) < 200:
        print("PDF extraction returned too little text — falling back to raw text.")
        return [text]

    # 2. Robust segmentation: split on paragraphs OR sentences OR fallback
    segments = re.split(r"\n\n+|\. ", text)
    segments = [s.strip() for s in segments if len(s.strip()) > 50]

    # Fallback if segmentation failed
    if len(segments) < 3:
        print("Too few segments — falling back to fixed-size chunks.")
        return [text[i:i+800] for i in range(0, len(text), 800)]

    # 3. Embedder (single-sequence)
    embedder = OllamaEmbeddings(model=MODELS["embed"])

    print("Generating embeddings...")
    # embeddings = [np.array(embedder.embed_query(seg)) for seg in segments]
    embeddings = []
    print("Embedding segments:", end=" ", flush=True)
    for i, seg in enumerate(segments, start=1):
        emb = embedder.embed_query(seg)
        embeddings.append(np.array(emb))

        if i % 10 == 0:
            print("•", end="", flush=True)   # bullet every 10
        else:
            print(".", end="", flush=True)
    print(f" done ({len(segments)} segments).")
    print(f"Generated {len(embeddings)} embeddings.")

    # 4. Compute similarities
    sims = []
    for i in range(1, len(embeddings)):
        a, b = embeddings[i-1], embeddings[i]
        sim = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
        sims.append(sim)

    # Fallback if similarity cannot be computed
    if len(sims) == 0:
        print("Similarity array empty — falling back to fixed-size chunks.")
        return [text[i:i+800] for i in range(0, len(text), 800)]

    # 5. Semantic breakpoints
    threshold = np.percentile(sims, 25)

    chunks = []
    current = [segments[0]]

    for i in range(1, len(segments)):
        if sims[i-1] < threshold:
            chunks.append(" ".join(current))
            current = []
        current.append(segments[i])

    if current:
        chunks.append(" ".join(current))

    return [c for c in chunks if len(c.strip()) > 80]

# --- 1. DATA ACQUISITION & CHUNKING ---
def setup_corpus():
    all_chunks = []
    # splitter = RecursiveCharacterTextSplitter(
    #     chunk_size=1200,
    #     chunk_overlap=200,
    #     separators=["\nArt. ", "\nSection ", "\n\n", ". "]
    # )

    for name, url in SOURCES.items():
        path = f"../docs/{name}.pdf"
        if not os.path.exists(path):
            print(f"Document {name} does not exist!")
            raise Exception(f"Document {name} does not exist!")
            # r = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'})
            # with open(path, 'wb') as f: f.write(r.content)
       
        print(f"Chunking {name}...")
        #reader = PdfReader(path)
        #text = "".join([p.extract_text() for p in reader.pages])
        doc_chunks = get_semantic_chunks(path) #splitter.split_text(text)
       
        for i, content in enumerate(doc_chunks):
            all_chunks.append({
                "id": f"{name}_{i}",
                "text": content,
                "source": name,
                "embedding": None # Will fill in next step
            })
    return all_chunks

# --- 2. EMBEDDING & CLUSTERING (THE SEMANTIC GRAPH) ---
def build_communities(chunks):
    print(f"Embedding {len(chunks)} local chunks...")
    for c in chunks:
        # Nomic requirement: prepend 'search_document: ' for indexing
        res = ollama.embeddings(model=MODELS["embed"], prompt=f"search_document: {c['text']}")
        c["embedding"] = res["embedding"]

    # Cluster chunks into "Communities" (Themes)
    # Heuristic: 1 community per ~15 chunks
    num_clusters = max(6, len(chunks) // 15)
    embeddings_matrix = np.array([c["embedding"] for c in chunks])
   
    print(f"Clustering into {num_clusters} semantic communities...")
    kmeans = KMeans(n_clusters=num_clusters, random_state=42, n_init=10)
    labels = kmeans.fit_predict(embeddings_matrix)
   
    communities = []
    for i in range(num_clusters):
        community_members = [chunks[idx] for idx, label in enumerate(labels) if label == i]
        communities.append({
            "community_id": i,
            "member_ids": [m["id"] for m in community_members],
            "sample_text": "\n---\n".join([m["text"] for m in community_members[:4]]) # Top 4 for LLM
        })
    return communities

# --- 3. GLOBAL SUMMARIZATION & GLOBAL EMBEDDING ---
def summarize_and_index_communities(communities):
    print("Generating Community Reports and Global Embeddings...")
    for comm in communities:
        prompt = f"""
        Analyze these legal snippets and provide a structured JSON report:
        1. "title": Theme name (e.g. 'Risk Management')
        2. "summary": 2-sentence explanation of how this theme is handled.
        3. "findings": List 3 key obligations found.

        You MUST return valid JSON with exactly these keys:
        "title": string,
        "summary": string,
        "findings": list of 3 short bullet points.
     
        If unsure, guess based on the snippets:
        {comm['sample_text']}
        """
        # Generate Summary with 7B Model
        response = ollama.generate(model=MODELS["slm"], prompt=prompt, format="json")
        report = json.loads(response['response'])
        print(report)
        comm["metadata"] = report
       # Normalize findings into a list of strings
        normalized = []
        for item in report.get("findings", []):
            if isinstance(item, str):
                normalized.append(item)
            elif isinstance(item, dict):
                # take the first value or convert dict to readable string
                if len(item) == 1:
                    normalized.append(list(item.values())[0])
                else:
                    normalized.append(", ".join(f"{k}: {v}" for k, v in item.items()))
            else:
                normalized.append(str(item))

        report["findings"] = normalized
        # EMBED THE SUMMARY (This is your Global Search Tier)
        summary_combined = f"{report['title']} {report['summary']} {' '.join(report['findings'])}"
        res = ollama.embeddings(model=MODELS["embed"], prompt=f"search_document: {summary_combined}")
        comm["community_embedding"] = res["embedding"]
       
        # Clean up temporary text
        del comm["sample_text"]

# --- MAIN EXECUTION ---
if __name__ == "__main__":
    # 1. Chunk and Download
    print("\n=== 1. CHUNK AND DOWNLOAD ===")
    raw_chunks = setup_corpus()
   
    # 2. Local Embeddings & Clustering
    print("\n=== 2. LOCAL EMBEDDINGS & CLUSTERING ===")
    communities_data = build_communities(raw_chunks)
   
    # 3. Global Summaries & Global Embeddings
    print("\n=== 3. GLOBAL SUMMARIES & GLOBAL EMBEDDINGS ===")
    summarize_and_index_communities(communities_data)
   
    # 4. Final Save
    final_index = {
        "chunks": {c["id"]: {"text": c["text"], "source": c["source"], "vec": c["embedding"]} for c in raw_chunks},
        "communities": communities_data
    }
   
    with open("ai_reg_semantic_index.json", "w") as f:
        json.dump(final_index, f, indent=2)
   
    print("\nSUCCESS: Semantic Index Created.")
    print("File saved: ai_reg_semantic_index.json")


