""" The 'Semantic GraphRAG' Pipeline
 * Local Chunks: Embedded for specific "needle-in-a-haystack" retrieval.
 * Communities: Created via K-Means clustering of those chunks.
 * Community Reports: Generated by Llama 3.1 8B to describe the "theme" of the cluster.
 * Global Embeddings: The reports themselves are embedded, allowing you to search for themes rather than just keywords.
 """
import os
import json
import requests
import numpy as np
import ollama
from langchain_text_splitters import RecursiveCharacterTextSplitter
from pypdf import PdfReader
from sklearn.cluster import KMeans

# --- CONFIGURATION ---
# Using 7B class for reasoning and Nomic for the 8k context window
MODELS = {
    "embed": "nomic-embed-text",
    "slm": "llama3.1:8b"
}

# The Corpus: EU (Horizontal), CoE (Treaty), and Switzerland (FADP + Guidelines)
SOURCES = {
    "EU_AI_Act": "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32024R1689",
    "CoE_AI_Convention": "https://rm.coe.int/1680afae3c",
    "Swiss_FADP": "https://www.fedlex.admin.ch/filestore/fedlex.data.admin.ch/eli/cc/2022/491/20230901/en/pdf-a/fedlex-data-admin-ch-eli-cc-2022-491-20230901-en-pdf-a.pdf",
    "Swiss_AI_Guidelines": "https://www.sbfi.admin.ch/dam/sbfi/en/dokumente/2020/11/leitlinien-ki.pdf"
}

# --- 1. DATA ACQUISITION & CHUNKING ---
def setup_corpus():
    all_chunks = []
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=1200,
        chunk_overlap=200,
        separators=["\nArt. ", "\nSection ", "\n\n", ". "]
    )

    for name, url in SOURCES.items():
        path = f"{name}.pdf"
        if not os.path.exists(path):
            print(f"Downloading {name}...")
            r = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'})
            with open(path, 'wb') as f: f.write(r.content)
       
        print(f"Chunking {name}...")
        reader = PdfReader(path)
        text = "".join([p.extract_text() for p in reader.pages])
        doc_chunks = splitter.split_text(text)
       
        for i, content in enumerate(doc_chunks):
            all_chunks.append({
                "id": f"{name}_{i}",
                "text": content,
                "source": name,
                "embedding": None # Will fill in next step
            })
    return all_chunks

# --- 2. EMBEDDING & CLUSTERING (THE SEMANTIC GRAPH) ---
def build_communities(chunks):
    print(f"Embedding {len(chunks)} local chunks...")
    for c in chunks:
        # Nomic requirement: prepend 'search_document: ' for indexing
        res = ollama.embeddings(model=MODELS["embed"], prompt=f"search_document: {c['text']}")
        c["embedding"] = res["embedding"]

    # Cluster chunks into "Communities" (Themes)
    # Heuristic: 1 community per ~15 chunks
    num_clusters = max(6, len(chunks) // 15)
    embeddings_matrix = np.array([c["embedding"] for c in chunks])
   
    print(f"Clustering into {num_clusters} semantic communities...")
    kmeans = KMeans(n_clusters=num_clusters, random_state=42, n_init=10)
    labels = kmeans.fit_predict(embeddings_matrix)
   
    communities = []
    for i in range(num_clusters):
        community_members = [chunks[idx] for idx, label in enumerate(labels) if label == i]
        communities.append({
            "community_id": i,
            "member_ids": [m["id"] for m in community_members],
            "sample_text": "\n---\n".join([m["text"] for m in community_members[:4]]) # Top 4 for LLM
        })
    return communities

# --- 3. GLOBAL SUMMARIZATION & GLOBAL EMBEDDING ---
def summarize_and_index_communities(communities):
    print("Generating Community Reports and Global Embeddings...")
    for comm in communities:
        prompt = f"""
        Analyze these legal snippets and provide a structured JSON report:
        1. "title": Theme name (e.g. 'Risk Management')
        2. "summary": 2-sentence explanation of how this theme is handled.
        3. "findings": List 3 key obligations found.
       
        Snippets:
        {comm['sample_text']}
        """
        # Generate Summary with 7B Model
        response = ollama.generate(model=MODELS["slm"], prompt=prompt, format="json")
        report = json.loads(response['response'])
        comm["metadata"] = report
       
        # EMBED THE SUMMARY (This is your Global Search Tier)
        summary_combined = f"{report['title']} {report['summary']} {' '.join(report['findings'])}"
        res = ollama.embeddings(model=MODELS["embed"], prompt=f"search_document: {summary_combined}")
        comm["community_embedding"] = res["embedding"]
       
        # Clean up temporary text
        del comm["sample_text"]

# --- MAIN EXECUTION ---
if __name__ == "__main__":
    # 1. Chunk and Download
    print("\n=== 1. CHUNK AND DOWNLOAD ===")
    raw_chunks = setup_corpus()
   
    # 2. Local Embeddings & Clustering
    print("\n=== 2. LOCAL EMBEDDINGS & CLUSTERING ===")
    communities_data = build_communities(raw_chunks)
   
    # 3. Global Summaries & Global Embeddings
    print("\n=== 3. GLOBAL SUMMARIES & GLOBAL EMBEDDINGS ===")
    summarize_and_index_communities(communities_data)
   
    # 4. Final Save
    final_index = {
        "chunks": {c["id"]: {"text": c["text"], "source": c["source"], "vec": c["embedding"]} for c in raw_chunks},
        "communities": communities_data
    }
   
    with open("ai_reg_semantic_index.json", "w") as f:
        json.dump(final_index, f, indent=2)
   
    print("\nSUCCESS: Semantic Index Created.")
    print("File saved: ai_reg_semantic_index.json")


